### ISSUE TITLE
Not Showing up in Obsidian Community Plugins

### ISSUE THREAD

**Issue by Aethrael** [MikeBirdTech/obsidian-open-interpreter#1]
![image](https://github.com/user-attachments/assets/6ce4ee6d-a600-4e74-8b4e-53840a2f282c)

**Comment by MikeBirdTech** [comment]
Still waiting on human review!

But you can install it on your local if you want

https://github.com/obsidianmd/obsidian-releases/pull/4052

**Comment by Aethrael** [comment]
Ah I see. I'm trying to get it working, but I'm a noob. I was thinking it
would be cool to get it working in combination with smart connections.

Appreciate the response!

**Comment by MikeBirdTech** [comment]
@Aethrael 

We are live! 

obsidian://show-plugin?id=open-interpreter
