### ISSUE TITLE
Mobile Device Compatibility

### ISSUE THREAD

**Issue by LeonelRFF** [MikeBirdTech/obsidian-open-interpreter#2]
Hello, first of all, excellent plugin, I would like to ask what is the compatibility with mobile devices, I tried to download it on my phone but it shows a message that says “This plugin does not support your device”. My phone is an [Oppo Reno 7](https://www.oppo.com/latin/smartphones/series-reno/reno7/specs/#)
Greetings.

**Comment by MikeBirdTech** [comment]
Not compatible on mobile in its current form. Would be amazing though! I'll be sure to let you know when it is
