### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Johannnnes** [MikeBirdTech/obsidian-open-interpreter#5]
Hi, this plugin looks awesome!

I get the message "Failed to install" though when trying to install via Obsidian Version 1.7.4..

Anything I can do?

**Comment by MikeBirdTech** [comment]
Oof sorry to hear that @Johannnnes 

I just tried on a test vault and am getting the same error. Not much info in the console so I'll do some digging! I did make an update yesterday so I might just need to revert. Will let you know when I get it working!

**Comment by MikeBirdTech** [comment]
@Johannnnes I forgot to add assets to the new release. Should work now!
