### ISSUE TITLE
Can we add Openrouter as LLM API provider?

### ISSUE THREAD

**Issue by chenyuz3** [MikeBirdTech/obsidian-open-interpreter#6]
Hi Mike,

As a heavy openrouter user I wonder if we can add openrouter as an API option, or in general just offer a customizable API url option? 

Best regards,
Chenyu

**Comment by MikeBirdTech** [comment]
Great idea @chenyuz3!

I don't think I'll have capacity to get to this until later in the week or maybe early next week. If you're up for making a PR, I'd love the contribution.

**Comment by MikeBirdTech** [comment]
@mentatbot can you please add a customizable API url option so users can point to their LLM of choice?
